# Generated by Django 4.2.7 on 2023-11-15 15:59

from django.db import migrations
from django.utils import timezone

t = [
    'Услуги',
    'Кэшбек',
    'Сантехника',
    'Материалы',
    'Работы'
]

def insert_types_data(apps, schema_editor):
    types = apps.get_model('form', 'Types')
    for i in t:
        types.objects.create(type_name=i)

def insert_test_row(apps, schema_editor):
    
    types = apps.get_model('form', 'Types')
    purcs = apps.get_model('form', 'Purchases')
    purcs.objects.create(day = timezone.now(), amount = 100.1, types = types.objects.get(pk = 21), info = 'test discription')
    

class Migration(migrations.Migration):
    dependencies = [
        ("form", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(insert_types_data),
        #migrations.RunPython(insert_test_row)
    ]
